[changelog]
body = """
{% for group, commits in commits | group_by(attribute="group") %}
### {{ group | striptags | trim | upper_first }}
{% for commit in commits %}\
- {% if commit.scope %}*({{ commit.scope }})*: {% endif %}\
{% if commit.breaking %}[**breaking**] {% endif %}\
{{ commit.message | upper_first }}\
([{{ commit.id | truncate(length=7, end="") }}](https://github.com/Dcatfly/weixin_bot_plugin/commit/{{ commit.id }}))
{% endfor %}
{% endfor %}
"""
trim = true

[git]
conventional_commits = true
filter_unconventional = true
split_commits = false
commit_parsers = [
    { message = "^feat", group = "<!-- 0 -->🚀 Features" },
    { message = "^fix", group = "<!-- 1 -->🐛 Bug Fixes" },
    { message = "^perf", group = "<!-- 2 -->⚡ Performance" },
    { message = "^refactor", group = "<!-- 3 -->🔨 Refactoring" },
    { message = "^doc", group = "<!-- 4 -->📚 Documentation" },
    { message = "^style", group = "<!-- 5 -->🎨 Styling" },
    { message = "^test", group = "<!-- 6 -->🧪 Testing" },
    { message = "^ci", group = "<!-- 7 -->⚙️ CI/CD" },
    { message = "^chore\\(release\\)", skip = true },
    { message = "^chore", group = "<!-- 8 -->📦 Miscellaneous" },
    { message = "^Merge", skip = true },
]
filter_commits = false
tag_pattern = "v[0-9].*"
sort_commits = "oldest"
